[pytest]
base_url = https://www.automationexercise.com
addopts = --base-url=https://www.automationexercise.com --screenshot=only-on-failure --tracing=retain-on-failure --video=retain-on-failure --output=test-results --dist=loadgroup
testpaths = tests
pythonpath = .
